using Godot;
using PKHeX.Core;
using PKHeX.Facade.Extensions;
using PKHeX.Facade.Pokemons;

namespace PKHeX.Godot.Scripts.Extensions;

public static class PokemonExtensions
{
    public static string GetSpritePath(this Pokemon pokemon)
    {
        var pkm = pokemon.Pkm;
        var species = pokemon.Species.Id;

        var isFemale = pkm.Gender is (int)Gender.Female;
        var isShiny = pkm.IsShiny;

        var basePath = isShiny
            ? "res://Assets/Sprites/Pokemon/Shiny"
            : "res://Assets/Sprites/Pokemon";

        var femalePath = $"{basePath}/Female/{species}.png";

        if (isFemale && !pokemon.Form.HasForm && ResourceLoader.Exists(femalePath))
            return femalePath;

        var path = $"{basePath}/{species}.png";

        if (!pokemon.Form.HasForm)
            return path;

        var mappedSpriteId = GetMappedSpriteId(pokemon);
        var formPath = $"{basePath}/{mappedSpriteId}.png";

        return ResourceLoader.Exists(formPath) ? formPath : $"{basePath}/{species}.png";
    }

    private static string GetMappedSpriteId(Pokemon pokemon)
    {
        return (pokemon.Species.Species, pokemon.Form.Form.Name) switch
        {
            (Species.Unown, "A") => "201-a",
            (Species.Unown, "B") => "201-b",
            (Species.Unown, "C") => "201-c",
            (Species.Unown, "D") => "201-d",
            (Species.Unown, "E") => "201-e",
            (Species.Unown, "F") => "201-f",
            (Species.Unown, "G") => "201-g",
            (Species.Unown, "H") => "201-h",
            (Species.Unown, "I") => "201-i",
            (Species.Unown, "J") => "201-j",
            (Species.Unown, "K") => "201-k",
            (Species.Unown, "L") => "201-l",
            (Species.Unown, "M") => "201-m",
            (Species.Unown, "N") => "201-n",
            (Species.Unown, "O") => "201-p",
            (Species.Unown, "P") => "201-p",
            (Species.Unown, "Q") => "201-q",
            (Species.Unown, "R") => "201-r",
            (Species.Unown, "S") => "201-s",
            (Species.Unown, "T") => "201-t",
            (Species.Unown, "U") => "201-u",
            (Species.Unown, "V") => "201-v",
            (Species.Unown, "W") => "201-w",
            (Species.Unown, "X") => "201-x",
            (Species.Unown, "Y") => "201-y",
            (Species.Unown, "Z") => "201-z",
            (Species.Unown, "!") => "201-!",
            (Species.Unown, "?") => "201-?",
            (Species.Burmy, "Plant") => "412-plant",
            (Species.Burmy, "Sandy") => "412-sandy",
            (Species.Burmy, "Trash") => "412-trash",
            (Species.Wormadam, "Plant") => "413-plant",
            (Species.Wormadam, "Sandy") => "413-sandy",
            (Species.Wormadam, "Trash") => "413-trash",
            (Species.Cherrim, "Overcast") => "421-overcast",
            (Species.Cherrim, "Sunshine") => "421-sunshine",
            (Species.Shellos, "East") => "422-east",
            (Species.Shellos, "West") => "422-west",
            (Species.Gastrodon, "East") => "423-east",
            (Species.Gastrodon, "West") => "423-west",
            (Species.Arceus, "Bug") => "493-bug",
            (Species.Arceus, "Dark") => "493-dark",
            (Species.Arceus, "Dragon") => "493-dragon",
            (Species.Arceus, "Electric") => "493-electric",
            (Species.Arceus, "Fairy") => "493-fairy",
            (Species.Arceus, "Fighting") => "493-fighting",
            (Species.Arceus, "Fire") => "493-fire",
            (Species.Arceus, "Flying") => "493-flying",
            (Species.Arceus, "Ghost") => "493-ghost",
            (Species.Arceus, "Grass") => "493-grass",
            (Species.Arceus, "Ground") => "493-ground",
            (Species.Arceus, "Ice") => "493-ice",
            (Species.Arceus, "Poison") => "493-poison",
            (Species.Arceus, "Psychic") => "493-psychic",
            (Species.Arceus, "Rock") => "493-rock",
            (Species.Arceus, "Steel") => "493-steel",
            (Species.Arceus, "Water") => "493-water",
            (Species.Arceus, "Legend") => "493-unknown",
            (Species.Deerling, "Autumn") => "585-autumn",
            (Species.Deerling, "Spring") => "585-spring",
            (Species.Deerling, "Summer") => "585-summer",
            (Species.Deerling, "Winter") => "585-winter",
            (Species.Sawsbuck, "Autumn") => "586-autumn",
            (Species.Sawsbuck, "Spring") => "586-spring",
            (Species.Sawsbuck, "Summer") => "586-summer",
            (Species.Sawsbuck, "Winter") => "586-winter",
            (Species.Genesect, "Water") => "649-douse",
            (Species.Genesect, "Electric") => "649-shock",
            (Species.Genesect, "Fire") => "649-burn",
            (Species.Genesect, "Ice") => "649-chill",
            (Species.Vivillon, "Archipelago") => "666-archipelago",
            (Species.Vivillon, "Continental") => "666-continental",
            (Species.Vivillon, "Elegant") => "666-elegant",
            (Species.Vivillon, "Fancy") => "666-fancy",
            (Species.Vivillon, "Garden") => "666-garden",
            (Species.Vivillon, "High Plains") => "666-high-plains",
            (Species.Vivillon, "Icy Snow") => "666-icy-snow",
            (Species.Vivillon, "Jungle") => "666-jungle",
            (Species.Vivillon, "Marine") => "666-marine",
            (Species.Vivillon, "Meadow") => "666-meadow",
            (Species.Vivillon, "Modern") => "666-modern",
            (Species.Vivillon, "Monsoon") => "666-monsoon",
            (Species.Vivillon, "Ocean") => "666-ocean",
            (Species.Vivillon, "Pok? Ball") => "666-poke-ball",
            (Species.Vivillon, "Polar") => "666-polar",
            (Species.Vivillon, "River") => "666-river",
            (Species.Vivillon, "Sandstorm") => "666-sandstorm",
            (Species.Vivillon, "Savanna") => "666-savanna",
            (Species.Vivillon, "Sun") => "666-sun",
            (Species.Vivillon, "Tundra") => "666-tundra",
            (Species.Flabébé, "Red") => "669-red",
            (Species.Flabébé, "Yellow") => "669-yellow",
            (Species.Flabébé, "Orange") => "669-orange",
            (Species.Flabébé, "Blue") => "669-blue",
            (Species.Flabébé, "White") => "669-white",
            (Species.Floette, "Red") => "670-red",
            (Species.Floette, "Yellow") => "670-yellow",
            (Species.Floette, "Orange") => "670-orange",
            (Species.Floette, "Blue") => "670-blue",
            (Species.Floette, "White") => "670-white",
            (Species.Florges, "Red") => "671-red",
            (Species.Florges, "Yellow") => "671-yellow",
            (Species.Florges, "Orange") => "671-orange",
            (Species.Florges, "Blue") => "671-blue",
            (Species.Florges, "White") => "671-white",
            (Species.Furfrou, "Dandy") => "676-dandy",
            (Species.Furfrou, "Debutante") => "676-debutante",
            (Species.Furfrou, "Diamond") => "676-diamond",
            (Species.Furfrou, "Heart") => "676-heart",
            (Species.Furfrou, "Kabuki") => "676-kabuki",
            (Species.Furfrou, "La Reine") => "676-la-reine",
            (Species.Furfrou, "Matron") => "676-matron",
            (Species.Furfrou, "Natural") => "676-natural",
            (Species.Furfrou, "Pharaoh") => "676-pharaoh",
            (Species.Furfrou, "Star") => "676-star",
            (Species.Xerneas, "Neutral") => "716-neutral",
            (Species.Xerneas, "Active") => "716-active",
            (Species.TypeNull, "Bug") => "773-bug",
            (Species.TypeNull, "Dark") => "773-dark",
            (Species.TypeNull, "Dragon") => "773-dragon",
            (Species.TypeNull, "Electric") => "773-electric",
            (Species.TypeNull, "Fairy") => "773-fairy",
            (Species.TypeNull, "Fighting") => "773-fighting",
            (Species.TypeNull, "Fire") => "773-fire",
            (Species.TypeNull, "Flying") => "773-flying",
            (Species.TypeNull, "Ghost") => "773-ghost",
            (Species.TypeNull, "Grass") => "773-grass",
            (Species.TypeNull, "Ground") => "773-ground",
            (Species.TypeNull, "Ice") => "773-ice",
            (Species.TypeNull, "Normal") => "773-normal",
            (Species.TypeNull, "Poison") => "773-poison",
            (Species.TypeNull, "Psychic") => "773-psychic",
            (Species.TypeNull, "Rock") => "773-rock",
            (Species.TypeNull, "Steel") => "773-steel",
            (Species.TypeNull, "Water") => "773-water",
            (Species.Cramorant, "Gorging") => "845-gorging",
            (Species.Cramorant, "Gulping") => "845-gulping",
            (Species.Alcremie, _) => GetAlcremieSprite(pokemon),
            (Species.Morpeko, "Hangry") => "877-hangry",
            (Species.Zarude, "Dada") => "893-dada",
            (Species.Deoxys, "Attack") => "10001",
            (Species.Deoxys, "Defense") => "10002",
            (Species.Deoxys, "Speed") => "10003",
            //(Species.Wormadam, "Sandy") => "10004",
            //(Species.Wormadam, "Trash") => "10005",
            (Species.Shaymin, "Sky") => "10006",
            (Species.Giratina, "Origin") => "10007",
            (Species.Rotom, "Heat") => "10008",
            (Species.Rotom, "Wash") => "10009",
            (Species.Rotom, "Frost") => "10010",
            (Species.Rotom, "Fan") => "10011",
            (Species.Rotom, "Mow") => "10012",
            (Species.Castform, "Sunny") => "10013",
            (Species.Castform, "Rainy") => "10014",
            (Species.Castform, "Snowy") => "10015",
            (Species.Basculin, "Blue") => "10016",
            (Species.Darmanitan, "Zen") => "10017",
            (Species.Meloetta, "Pirouette") => "10018",
            (Species.Tornadus, "Therian") => "10019",
            (Species.Thundurus, "Therian") => "10020",
            (Species.Landorus, "Therian") => "10021",
            (Species.Kyurem, "Black") => "10022",
            (Species.Kyurem, "White") => "10023",
            (Species.Keldeo, "Resolute") => "10024",
            (Species.Aegislash, "Blade") => "10026",
            (Species.Pumpkaboo, "Small") => "10027",
            (Species.Pumpkaboo, "Large") => "10028",
            (Species.Pumpkaboo, "Super") => "10029",
            (Species.Gourgeist, "Small") => "10030",
            (Species.Gourgeist, "Large") => "10031",
            (Species.Gourgeist, "Super") => "10032",
            (Species.Venusaur, "Mega") => "10033",
            (Species.Charizard, "Mega X") => "10034",
            (Species.Charizard, "Mega Y") => "10035",
            (Species.Blastoise, "Mega") => "10036",
            (Species.Alakazam, "Mega") => "10037",
            (Species.Gengar, "Mega") => "10038",
            (Species.Kangaskhan, "Mega") => "10039",
            (Species.Pinsir, "Mega") => "10040",
            (Species.Gyarados, "Mega") => "10041",
            (Species.Aerodactyl, "Mega") => "10042",
            (Species.Mewtwo, "Mega X") => "10043",
            (Species.Mewtwo, "Mega Y") => "10044",
            (Species.Ampharos, "Mega") => "10045",
            (Species.Scizor, "Mega") => "10046",
            (Species.Heracross, "Mega") => "10047",
            (Species.Houndoom, "Mega") => "10048",
            (Species.Tyranitar, "Mega") => "10049",
            (Species.Blaziken, "Mega") => "10050",
            (Species.Gardevoir, "Mega") => "10051",
            (Species.Mawile, "Mega") => "10052",
            (Species.Aggron, "Mega") => "10053",
            (Species.Medicham, "Mega") => "10054",
            (Species.Manectric, "Mega") => "10055",
            (Species.Banette, "Mega") => "10056",
            (Species.Absol, "Mega") => "10057",
            (Species.Garchomp, "Mega") => "10058",
            (Species.Lucario, "Mega") => "10059",
            (Species.Abomasnow, "Mega") => "10060",
            (Species.Floette, "Eternal") => "10061",
            (Species.Latias, "Mega") => "10062",
            (Species.Latios, "Mega") => "10063",
            (Species.Swampert, "Mega") => "10064",
            (Species.Sceptile, "Mega") => "10065",
            (Species.Sableye, "Mega") => "10066",
            (Species.Altaria, "Mega") => "10067",
            (Species.Gallade, "Mega") => "10068",
            (Species.Audino, "Mega") => "10069",
            (Species.Sharpedo, "Mega") => "10070",
            (Species.Slowbro, "Mega") => "10071",
            (Species.Steelix, "Mega") => "10072",
            (Species.Pidgeot, "Mega") => "10073",
            (Species.Glalie, "Mega") => "10074",
            (Species.Diancie, "Mega") => "10075",
            (Species.Metagross, "Mega") => "10076",
            (Species.Kyogre, "Primal") => "10077",
            (Species.Groudon, "Primal") => "10078",
            (Species.Rayquaza, "Mega") => "10079",
            (Species.Pikachu, "Rock Star") => "10080",
            (Species.Pikachu, "Belle") => "10081",
            (Species.Pikachu, "Pop Star") => "10082",
            (Species.Pikachu, "Ph.D.") => "10083",
            (Species.Pikachu, "Libre") => "10084",
            (Species.Pikachu, "Cosplay") => "10085",
            (Species.Hoopa, "Unbound") => "10086",
            (Species.Camerupt, "Mega") => "10087",
            (Species.Lopunny, "Mega") => "10088",
            (Species.Salamence, "Mega") => "10089",
            (Species.Beedrill, "Mega") => "10090",
            (Species.Rattata, "Alola") => "10091",
            (Species.Raticate, "Alola") => "10092",
            (Species.Raticate, "Large") => "10093",
            (Species.Pikachu, "Original") => "10094",
            (Species.Pikachu, "Hoenn") => "10095",
            (Species.Pikachu, "Sinnoh") => "10096",
            (Species.Pikachu, "Unova") => "10097",
            (Species.Pikachu, "Kalos") => "10098",
            (Species.Pikachu, "Alola") => "10099",
            (Species.Raichu, "Alola") => "10100",
            (Species.Sandshrew, "Alola") => "10101",
            (Species.Sandslash, "Alola") => "10102",
            (Species.Vulpix, "Alola") => "10103",
            (Species.Ninetales, "Alola") => "10104",
            (Species.Diglett, "Alola") => "10105",
            (Species.Dugtrio, "Alola") => "10106",
            (Species.Meowth, "Alola") => "10107",
            (Species.Persian, "Alola") => "10108",
            (Species.Geodude, "Alola") => "10109",
            (Species.Graveler, "Alola") => "10110",
            (Species.Golem, "Alola") => "10111",
            (Species.Grimer, "Alola") => "10112",
            (Species.Muk, "Alola") => "10113",
            (Species.Exeggutor, "Alola") => "10114",
            (Species.Marowak, "Alola") => "10115",
            (Species.Greninja, "Active") => "10116",
            (Species.Greninja, "Ash") => "10117",
            (Species.Zygarde, "10%-C") => "10118",
            (Species.Zygarde, "50%-C") => "10119",
            (Species.Zygarde, "Complete") => "10120",
            (Species.Gumshoos, "Large") => "10121",
            (Species.Vikavolt, "Large") => "10122",
            (Species.Oricorio, "Pom-Pom") => "10123",
            (Species.Oricorio, "Pa?u") => "10124",
            (Species.Oricorio, "Sensu") => "10125",
            (Species.Lycanroc, "Midnight") => "10126",
            (Species.Wishiwashi, "School") => "10127",
            (Species.Lurantis, "Large") => "10128",
            (Species.Salazzle, "Large") => "10129",
            (Species.Minior, "M-Orange") => "10130",
            (Species.Minior, "M-Yellow") => "10131",
            (Species.Minior, "M-Green") => "10132",
            (Species.Minior, "M-Blue") => "10133",
            (Species.Minior, "M-Indigo") => "10134",
            (Species.Minior, "M-Violet") => "10135",
            (Species.Minior, "C-Red") => "10136",
            (Species.Minior, "C-Orange") => "10137",
            (Species.Minior, "C-Yellow") => "10138",
            (Species.Minior, "C-Green") => "10139",
            (Species.Minior, "C-Blue") => "10140",
            (Species.Minior, "C-Indigo") => "10141",
            (Species.Minior, "C-Violet") => "10142",
            (Species.Mimikyu, "Busted") => "10143",
            (Species.Mimikyu, "Large") => "10144",
            (Species.Mimikyu, "*Busted") => "10145",
            (Species.Kommoo, "Large") => "10146",
            (Species.Magearna, "Original") => "10147",
            (Species.Pikachu, "Partner") => "10148",
            (Species.Marowak, "Large") => "10149",
            (Species.Ribombee, "Large") => "10150",
            (Species.Rockruff, "Dusk") => "10151",
            (Species.Lycanroc, "Dusk") => "10152",
            (Species.Araquanid, "Large") => "10153",
            (Species.Togedemaru, "Large") => "10154",
            (Species.Necrozma, "Dusk") => "10155",
            (Species.Necrozma, "Dawn") => "10156",
            (Species.Necrozma, "Ultra") => "10157",
            (Species.Meowth, "Galar") => "10161",
            (Species.Ponyta, "Galar") => "10162",
            (Species.Rapidash, "Galar") => "10163",
            (Species.Slowpoke, "Galar") => "10164",
            (Species.Slowbro, "Galar") => "10165",
            (Species.Farfetchd, "Galar") => "10166",
            (Species.Weezing, "Galar") => "10167",
            (Species.MrMime, "Galar") => "10168",
            (Species.Articuno, "Galar") => "10169",
            (Species.Zapdos, "Galar") => "10170",
            (Species.Moltres, "Galar") => "10171",
            (Species.Slowking, "Galar") => "10172",
            (Species.Corsola, "Galar") => "10173",
            (Species.Zigzagoon, "Galar") => "10174",
            (Species.Linoone, "Galar") => "10175",
            (Species.Darumaka, "Galar") => "10176",
            (Species.Darmanitan, "Galar") => "10177",
            (Species.Darmanitan, "Galar Zen") => "10178",
            (Species.Yamask, "Galar") => "10179",
            (Species.Stunfisk, "Galar") => "10180",
            (Species.Zygarde, "10%") => "10181",
            //(Species.Cramorant, "Gulping") => "10182",
            //(Species.Cramorant, "Gorging") => "10183",
            (Species.Toxtricity, "Low Key") => "10184",
            (Species.Eiscue, "Noice Face") => "10185",
            //(Species.Morpeko, "Hangry") => "10187",
            (Species.Zacian, "Crowned") => "10188",
            (Species.Zamazenta, "Crowned") => "10189",
            (Species.Eternatus, "Eternamax") => "10190",
            (Species.Urshifu, "Rapid Strike") => "10191",
            //(Species.Zarude, "Dada") => "10192",
            (Species.Calyrex, "Ice") => "10193",
            (Species.Calyrex, "Shadow") => "10194",
            // gmax forms skipped [10195-10228]
            (Species.Growlithe, "Hisui") => "10229",
            (Species.Arcanine, "Hisui") => "10230",
            (Species.Voltorb, "Hisui") => "10231",
            (Species.Electrode, "Hisui") => "10232",
            (Species.Typhlosion, "Hisui") => "10233",
            (Species.Qwilfish, "Hisui") => "10234",
            (Species.Sneasel, "Hisui") => "10235",
            (Species.Samurott, "Hisui") => "10236",
            (Species.Lilligant, "Hisui") => "10237",
            (Species.Zorua, "Hisui") => "10238",
            (Species.Zoroark, "Hisui") => "10239",
            (Species.Braviary, "Hisui") => "10240",
            (Species.Sliggoo, "Hisui") => "10241",
            (Species.Goodra, "Hisui") => "10242",
            (Species.Avalugg, "Hisui") => "10243",
            (Species.Decidueye, "Hisui") => "10244",
            (Species.Dialga, "Origin") => "10245",
            (Species.Palkia, "Origin") => "10246",
            (Species.Basculin, "White") => "10247",
            (Species.Enamorus, "Therian") => "10249",
            (Species.Tauros, "Paldea Combat") => "10250",
            (Species.Tauros, "Paldea Blaze") => "10251",
            (Species.Tauros, "Paldea Aqua") => "10252",
            (Species.Wooper, "Paldea") => "10253",
            (Species.Dudunsparce, "Three-Segment") => "10255",
            (Species.Palafin, "Hero") => "10256",
            (Species.Maushold, "Family of Three") => "10257",
            (Species.Tatsugiri, "Droopy") => "10258",
            (Species.Tatsugiri, "Stretchy") => "10259",
            (Species.Squawkabilly, "Blue") => "10260",
            (Species.Squawkabilly, "Yellow") => "10261",
            (Species.Squawkabilly, "White") => "10262",
            (Species.Gimmighoul, "Roaming") => "10263",
            (Species.Koraidon, "Limited") => "10264",
            (Species.Koraidon, "Sprinting") => "10265",
            (Species.Koraidon, "Swimming") => "10266",
            (Species.Koraidon, "Gliding") => "10267",
            (Species.Miraidon, "Low-Power") => "10268",
            (Species.Miraidon, "Drive") => "10269",
            (Species.Miraidon, "Aquatic") => "10270",
            (Species.Miraidon, "Glide") => "10271",
            (Species.Ursaluna, "Bloodmoon") => "10272",
            (Species.Ogerpon, "Wellspring") => "10273",
            (Species.Ogerpon, "Hearthflame") => "10274",
            (Species.Ogerpon, "Cornerstone") => "10275",
            (Species.Terapagos, "Terastal") => "10276",
            (Species.Terapagos, "Stellar") => "10277",
            (Species.Clefable, "Mega") => "10278",
            (Species.Victreebel, "Mega") => "10279",
            (Species.Starmie, "Mega") => "10280",
            (Species.Dragonite, "Mega") => "10281",
            (Species.Meganium, "Mega") => "10282",
            (Species.Feraligatr, "Mega") => "10283",
            (Species.Skarmory, "Mega") => "10284",
            (Species.Froslass, "Mega") => "10285",
            (Species.Emboar, "Mega") => "10286",
            (Species.Excadrill, "Mega") => "10287",
            (Species.Scolipede, "Mega") => "10288",
            (Species.Scrafty, "Mega") => "10289",
            (Species.Eelektross, "Mega") => "10290",
            (Species.Chandelure, "Mega") => "10291",
            (Species.Chesnaught, "Mega") => "10292",
            (Species.Delphox, "Mega") => "10293",
            (Species.Greninja, "Mega") => "10294",
            (Species.Pyroar, "Mega") => "10295",
            (Species.Floette, "Mega") => "10296",
            (Species.Malamar, "Mega") => "10297",
            (Species.Barbaracle, "Mega") => "10298",
            (Species.Dragalge, "Mega") => "10299",
            (Species.Hawlucha, "Mega") => "10300",
            (Species.Zygarde, "Mega") => "10301",
            (Species.Drampa, "Mega") => "10302",
            (Species.Falinks, "Mega") => "10303",
            (Species.Raichu, "Mega X") => "10304",
            (Species.Raichu, "Mega Y") => "10305",
            (Species.Chimecho, "Mega") => "10306",
            (Species.Absol, "Mega Z") => "10307",
            (Species.Staraptor, "Mega") => "10308",
            (Species.Garchomp, "Mega Z") => "10309",
            (Species.Lucario, "Mega Z") => "10310",
            (Species.Heatran, "Mega") => "10311",
            (Species.Darkrai, "Mega") => "10312",
            (Species.Golurk, "Mega") => "10313",
            (Species.Meowstic, "Mega") => "10314",
            (Species.Crabominable, "Mega") => "10315",
            (Species.Golisopod, "Mega") => "10316",
            (Species.Magearna, "Normal-Mega") => "10317",
            (Species.Magearna, "Original-Mega") => "10318",
            (Species.Zeraora, "Mega") => "10319",
            (Species.Scovillain, "Mega") => "10320",
            (Species.Glimmora, "Mega") => "10321",
            (Species.Tatsugiri, "Curly-Mega") => "10322",
            (Species.Tatsugiri, "Droopy-Mega") => "10323",
            (Species.Tatsugiri, "Stretchy-Mega") => "10324",
            (Species.Baxcalibur, "Mega") => "10325",
            _ => pokemon.Species.Id.ToString()
        };
    }

    private static string GetAlcremieSprite(Pokemon pokemon)
    {
        if (pokemon.Pkm is not IFormArgument f)
            return Species.Alcremie.Id().ToString();

        var formArgument = f.FormArgument;

        var flavor = pokemon.Form.Form.Name switch
        {
            "Caramel Swirl" => "caramel-swirl",
            "Lemon Cream" => "lemon-cream",
            "Matcha Cream" => "matcha-cream",
            "Mint Cream" => "mint-cream",
            "Rainbow Swirl" => "rainbow-swirl",
            "Ruby Cream" => "ruby-cream",
            "Ruby Swirl" => "ruby-swirl",
            "Salted Cream" => "salted-cream",
            "Vanilla Cream" => "vanilla-cream",
            _ => null
        };

        var topping = (AlcremieDecoration)formArgument switch
        {
            AlcremieDecoration.Strawberry => "strawberry-sweet",
            AlcremieDecoration.Berry => "berry-sweet",
            AlcremieDecoration.Clover => "clover-sweet",
            AlcremieDecoration.Flower => "flower-sweet",
            AlcremieDecoration.Love => "love-sweet",
            AlcremieDecoration.Ribbon => "ribbon-sweet",
            AlcremieDecoration.Star => "star-sweet",
            _ => null
        };

        if (flavor is null || topping is null)
            return Species.Alcremie.Id().ToString();

        return $"{flavor}-{topping}";
    }
}
