using Godot;
using PKHeX.Core;
using PKHeX.Facade.Extensions;
using PKHeX.Facade.Pokemons;
using static PKHeX.Core.Species;

namespace PKHeX.Godot.Scripts.Extensions;

public static class PokemonExtensions
{
    public static string GetSpritePath(this Pokemon pokemon)
    {
        var pkm = pokemon.Pkm;
        var species = pokemon.Species.Id;

        var isFemale = pkm.Gender is (int)Gender.Female;
        var isShiny = pkm.IsShiny;

        var basePath = isShiny
            ? "res://Assets/Sprites/Pokemon/Shiny"
            : "res://Assets/Sprites/Pokemon";

        var femaleSpriteId = pokemon.GetFemaleSpriteId();

        if (isFemale && femaleSpriteId is not null)
            return $"{basePath}/Female/{species}.png";

        var path = $"{basePath}/{species}.png";

        if (!pokemon.Form.HasForm)
            return path;

        var mappedSpriteId = GetMappedSpriteId(pokemon);
        var formPath = $"{basePath}/{mappedSpriteId}.png";

        return ResourceLoader.Exists(formPath) ? formPath : path;
    }

    private static string GetMappedSpriteId(Pokemon pokemon)
    {
        return (pokemon.Species.Species, pokemon.Form.Form.Name) switch
        {
            (Unown, "A") => "201-a",
            (Unown, "B") => "201-b",
            (Unown, "C") => "201-c",
            (Unown, "D") => "201-d",
            (Unown, "E") => "201-e",
            (Unown, "F") => "201-f",
            (Unown, "G") => "201-g",
            (Unown, "H") => "201-h",
            (Unown, "I") => "201-i",
            (Unown, "J") => "201-j",
            (Unown, "K") => "201-k",
            (Unown, "L") => "201-l",
            (Unown, "M") => "201-m",
            (Unown, "N") => "201-n",
            (Unown, "O") => "201-p",
            (Unown, "P") => "201-p",
            (Unown, "Q") => "201-q",
            (Unown, "R") => "201-r",
            (Unown, "S") => "201-s",
            (Unown, "T") => "201-t",
            (Unown, "U") => "201-u",
            (Unown, "V") => "201-v",
            (Unown, "W") => "201-w",
            (Unown, "X") => "201-x",
            (Unown, "Y") => "201-y",
            (Unown, "Z") => "201-z",
            (Unown, "!") => "201-!",
            (Unown, "?") => "201-?",
            (Burmy, "Plant") => "412-plant",
            (Burmy, "Sandy") => "412-sandy",
            (Burmy, "Trash") => "412-trash",
            (Wormadam, "Plant") => "413-plant",
            (Wormadam, "Sandy") => "413-sandy",
            (Wormadam, "Trash") => "413-trash",
            (Cherrim, "Overcast") => "421-overcast",
            (Cherrim, "Sunshine") => "421-sunshine",
            (Shellos, "East") => "422-east",
            (Shellos, "West") => "422-west",
            (Gastrodon, "East") => "423-east",
            (Gastrodon, "West") => "423-west",
            (Arceus, "Bug") => "493-bug",
            (Arceus, "Dark") => "493-dark",
            (Arceus, "Dragon") => "493-dragon",
            (Arceus, "Electric") => "493-electric",
            (Arceus, "Fairy") => "493-fairy",
            (Arceus, "Fighting") => "493-fighting",
            (Arceus, "Fire") => "493-fire",
            (Arceus, "Flying") => "493-flying",
            (Arceus, "Ghost") => "493-ghost",
            (Arceus, "Grass") => "493-grass",
            (Arceus, "Ground") => "493-ground",
            (Arceus, "Ice") => "493-ice",
            (Arceus, "Poison") => "493-poison",
            (Arceus, "Psychic") => "493-psychic",
            (Arceus, "Rock") => "493-rock",
            (Arceus, "Steel") => "493-steel",
            (Arceus, "Water") => "493-water",
            (Arceus, "Legend") => "493-unknown",
            (Deerling, "Autumn") => "585-autumn",
            (Deerling, "Spring") => "585-spring",
            (Deerling, "Summer") => "585-summer",
            (Deerling, "Winter") => "585-winter",
            (Sawsbuck, "Autumn") => "586-autumn",
            (Sawsbuck, "Spring") => "586-spring",
            (Sawsbuck, "Summer") => "586-summer",
            (Sawsbuck, "Winter") => "586-winter",
            (Genesect, "Water") => "649-douse",
            (Genesect, "Electric") => "649-shock",
            (Genesect, "Fire") => "649-burn",
            (Genesect, "Ice") => "649-chill",
            (Vivillon, "Archipelago") => "666-archipelago",
            (Vivillon, "Continental") => "666-continental",
            (Vivillon, "Elegant") => "666-elegant",
            (Vivillon, "Fancy") => "666-fancy",
            (Vivillon, "Garden") => "666-garden",
            (Vivillon, "High Plains") => "666-high-plains",
            (Vivillon, "Icy Snow") => "666-icy-snow",
            (Vivillon, "Jungle") => "666-jungle",
            (Vivillon, "Marine") => "666-marine",
            (Vivillon, "Meadow") => "666-meadow",
            (Vivillon, "Modern") => "666-modern",
            (Vivillon, "Monsoon") => "666-monsoon",
            (Vivillon, "Ocean") => "666-ocean",
            (Vivillon, "Pok? Ball") => "666-poke-ball",
            (Vivillon, "Polar") => "666-polar",
            (Vivillon, "River") => "666-river",
            (Vivillon, "Sandstorm") => "666-sandstorm",
            (Vivillon, "Savanna") => "666-savanna",
            (Vivillon, "Sun") => "666-sun",
            (Vivillon, "Tundra") => "666-tundra",
            (Flabébé, "Red") => "669-red",
            (Flabébé, "Yellow") => "669-yellow",
            (Flabébé, "Orange") => "669-orange",
            (Flabébé, "Blue") => "669-blue",
            (Flabébé, "White") => "669-white",
            (Floette, "Red") => "670-red",
            (Floette, "Yellow") => "670-yellow",
            (Floette, "Orange") => "670-orange",
            (Floette, "Blue") => "670-blue",
            (Floette, "White") => "670-white",
            (Florges, "Red") => "671-red",
            (Florges, "Yellow") => "671-yellow",
            (Florges, "Orange") => "671-orange",
            (Florges, "Blue") => "671-blue",
            (Florges, "White") => "671-white",
            (Furfrou, "Dandy") => "676-dandy",
            (Furfrou, "Debutante") => "676-debutante",
            (Furfrou, "Diamond") => "676-diamond",
            (Furfrou, "Heart") => "676-heart",
            (Furfrou, "Kabuki") => "676-kabuki",
            (Furfrou, "La Reine") => "676-la-reine",
            (Furfrou, "Matron") => "676-matron",
            (Furfrou, "Natural") => "676-natural",
            (Furfrou, "Pharaoh") => "676-pharaoh",
            (Furfrou, "Star") => "676-star",
            (Xerneas, "Neutral") => "716-neutral",
            (Xerneas, "Active") => "716-active",
            (TypeNull, "Bug") => "773-bug",
            (TypeNull, "Dark") => "773-dark",
            (TypeNull, "Dragon") => "773-dragon",
            (TypeNull, "Electric") => "773-electric",
            (TypeNull, "Fairy") => "773-fairy",
            (TypeNull, "Fighting") => "773-fighting",
            (TypeNull, "Fire") => "773-fire",
            (TypeNull, "Flying") => "773-flying",
            (TypeNull, "Ghost") => "773-ghost",
            (TypeNull, "Grass") => "773-grass",
            (TypeNull, "Ground") => "773-ground",
            (TypeNull, "Ice") => "773-ice",
            (TypeNull, "Normal") => "773-normal",
            (TypeNull, "Poison") => "773-poison",
            (TypeNull, "Psychic") => "773-psychic",
            (TypeNull, "Rock") => "773-rock",
            (TypeNull, "Steel") => "773-steel",
            (TypeNull, "Water") => "773-water",
            (Cramorant, "Gorging") => "845-gorging",
            (Cramorant, "Gulping") => "845-gulping",
            (Alcremie, _) => GetAlcremieSprite(pokemon),
            (Morpeko, "Hangry") => "877-hangry",
            (Zarude, "Dada") => "893-dada",
            (Deoxys, "Attack") => "10001",
            (Deoxys, "Defense") => "10002",
            (Deoxys, "Speed") => "10003",
            //(Species.Wormadam, "Sandy") => "10004",
            //(Species.Wormadam, "Trash") => "10005",
            (Shaymin, "Sky") => "10006",
            (Giratina, "Origin") => "10007",
            (Rotom, "Heat") => "10008",
            (Rotom, "Wash") => "10009",
            (Rotom, "Frost") => "10010",
            (Rotom, "Fan") => "10011",
            (Rotom, "Mow") => "10012",
            (Castform, "Sunny") => "10013",
            (Castform, "Rainy") => "10014",
            (Castform, "Snowy") => "10015",
            (Basculin, "Blue") => "10016",
            (Darmanitan, "Zen") => "10017",
            (Meloetta, "Pirouette") => "10018",
            (Tornadus, "Therian") => "10019",
            (Thundurus, "Therian") => "10020",
            (Landorus, "Therian") => "10021",
            (Kyurem, "Black") => "10022",
            (Kyurem, "White") => "10023",
            (Keldeo, "Resolute") => "10024",
            (Aegislash, "Blade") => "10026",
            (Pumpkaboo, "Small") => "10027",
            (Pumpkaboo, "Large") => "10028",
            (Pumpkaboo, "Super") => "10029",
            (Gourgeist, "Small") => "10030",
            (Gourgeist, "Large") => "10031",
            (Gourgeist, "Super") => "10032",
            (Venusaur, "Mega") => "10033",
            (Charizard, "Mega X") => "10034",
            (Charizard, "Mega Y") => "10035",
            (Blastoise, "Mega") => "10036",
            (Alakazam, "Mega") => "10037",
            (Gengar, "Mega") => "10038",
            (Kangaskhan, "Mega") => "10039",
            (Pinsir, "Mega") => "10040",
            (Gyarados, "Mega") => "10041",
            (Aerodactyl, "Mega") => "10042",
            (Mewtwo, "Mega X") => "10043",
            (Mewtwo, "Mega Y") => "10044",
            (Ampharos, "Mega") => "10045",
            (Scizor, "Mega") => "10046",
            (Heracross, "Mega") => "10047",
            (Houndoom, "Mega") => "10048",
            (Tyranitar, "Mega") => "10049",
            (Blaziken, "Mega") => "10050",
            (Gardevoir, "Mega") => "10051",
            (Mawile, "Mega") => "10052",
            (Aggron, "Mega") => "10053",
            (Medicham, "Mega") => "10054",
            (Manectric, "Mega") => "10055",
            (Banette, "Mega") => "10056",
            (Absol, "Mega") => "10057",
            (Garchomp, "Mega") => "10058",
            (Lucario, "Mega") => "10059",
            (Abomasnow, "Mega") => "10060",
            (Floette, "Eternal") => "10061",
            (Latias, "Mega") => "10062",
            (Latios, "Mega") => "10063",
            (Swampert, "Mega") => "10064",
            (Sceptile, "Mega") => "10065",
            (Sableye, "Mega") => "10066",
            (Altaria, "Mega") => "10067",
            (Gallade, "Mega") => "10068",
            (Audino, "Mega") => "10069",
            (Sharpedo, "Mega") => "10070",
            (Slowbro, "Mega") => "10071",
            (Steelix, "Mega") => "10072",
            (Pidgeot, "Mega") => "10073",
            (Glalie, "Mega") => "10074",
            (Diancie, "Mega") => "10075",
            (Metagross, "Mega") => "10076",
            (Kyogre, "Primal") => "10077",
            (Groudon, "Primal") => "10078",
            (Rayquaza, "Mega") => "10079",
            (Pikachu, "Rock Star") => "10080",
            (Pikachu, "Belle") => "10081",
            (Pikachu, "Pop Star") => "10082",
            (Pikachu, "Ph.D.") => "10083",
            (Pikachu, "Libre") => "10084",
            (Pikachu, "Cosplay") => "10085",
            (Hoopa, "Unbound") => "10086",
            (Camerupt, "Mega") => "10087",
            (Lopunny, "Mega") => "10088",
            (Salamence, "Mega") => "10089",
            (Beedrill, "Mega") => "10090",
            (Rattata, "Alola") => "10091",
            (Raticate, "Alola") => "10092",
            (Raticate, "Large") => "10093",
            (Pikachu, "Original") => "10094",
            (Pikachu, "Hoenn") => "10095",
            (Pikachu, "Sinnoh") => "10096",
            (Pikachu, "Unova") => "10097",
            (Pikachu, "Kalos") => "10098",
            (Pikachu, "Alola") => "10099",
            (Raichu, "Alola") => "10100",
            (Sandshrew, "Alola") => "10101",
            (Sandslash, "Alola") => "10102",
            (Vulpix, "Alola") => "10103",
            (Ninetales, "Alola") => "10104",
            (Diglett, "Alola") => "10105",
            (Dugtrio, "Alola") => "10106",
            (Meowth, "Alola") => "10107",
            (Persian, "Alola") => "10108",
            (Geodude, "Alola") => "10109",
            (Graveler, "Alola") => "10110",
            (Golem, "Alola") => "10111",
            (Grimer, "Alola") => "10112",
            (Muk, "Alola") => "10113",
            (Exeggutor, "Alola") => "10114",
            (Marowak, "Alola") => "10115",
            (Greninja, "Active") => "10116",
            (Greninja, "Ash") => "10117",
            (Zygarde, "10%-C") => "10118",
            (Zygarde, "50%-C") => "10119",
            (Zygarde, "Complete") => "10120",
            (Gumshoos, "Large") => "10121",
            (Vikavolt, "Large") => "10122",
            (Oricorio, "Pom-Pom") => "10123",
            (Oricorio, "Pa?u") => "10124",
            (Oricorio, "Sensu") => "10125",
            (Lycanroc, "Midnight") => "10126",
            (Wishiwashi, "School") => "10127",
            (Lurantis, "Large") => "10128",
            (Salazzle, "Large") => "10129",
            (Minior, "M-Orange") => "10130",
            (Minior, "M-Yellow") => "10131",
            (Minior, "M-Green") => "10132",
            (Minior, "M-Blue") => "10133",
            (Minior, "M-Indigo") => "10134",
            (Minior, "M-Violet") => "10135",
            (Minior, "C-Red") => "10136",
            (Minior, "C-Orange") => "10137",
            (Minior, "C-Yellow") => "10138",
            (Minior, "C-Green") => "10139",
            (Minior, "C-Blue") => "10140",
            (Minior, "C-Indigo") => "10141",
            (Minior, "C-Violet") => "10142",
            (Mimikyu, "Busted") => "10143",
            (Mimikyu, "Large") => "10144",
            (Mimikyu, "*Busted") => "10145",
            (Kommoo, "Large") => "10146",
            (Magearna, "Original") => "10147",
            (Pikachu, "Partner") => "10148",
            (Marowak, "Large") => "10149",
            (Ribombee, "Large") => "10150",
            (Rockruff, "Dusk") => "10151",
            (Lycanroc, "Dusk") => "10152",
            (Araquanid, "Large") => "10153",
            (Togedemaru, "Large") => "10154",
            (Necrozma, "Dusk") => "10155",
            (Necrozma, "Dawn") => "10156",
            (Necrozma, "Ultra") => "10157",
            (Meowth, "Galar") => "10161",
            (Ponyta, "Galar") => "10162",
            (Rapidash, "Galar") => "10163",
            (Slowpoke, "Galar") => "10164",
            (Slowbro, "Galar") => "10165",
            (Farfetchd, "Galar") => "10166",
            (Weezing, "Galar") => "10167",
            (MrMime, "Galar") => "10168",
            (Articuno, "Galar") => "10169",
            (Zapdos, "Galar") => "10170",
            (Moltres, "Galar") => "10171",
            (Slowking, "Galar") => "10172",
            (Corsola, "Galar") => "10173",
            (Zigzagoon, "Galar") => "10174",
            (Linoone, "Galar") => "10175",
            (Darumaka, "Galar") => "10176",
            (Darmanitan, "Galar") => "10177",
            (Darmanitan, "Galar Zen") => "10178",
            (Yamask, "Galar") => "10179",
            (Stunfisk, "Galar") => "10180",
            (Zygarde, "10%") => "10181",
            //(Species.Cramorant, "Gulping") => "10182",
            //(Species.Cramorant, "Gorging") => "10183",
            (Toxtricity, "Low Key") => "10184",
            (Eiscue, "Noice Face") => "10185",
            //(Species.Morpeko, "Hangry") => "10187",
            (Zacian, "Crowned") => "10188",
            (Zamazenta, "Crowned") => "10189",
            (Eternatus, "Eternamax") => "10190",
            (Urshifu, "Rapid Strike") => "10191",
            //(Species.Zarude, "Dada") => "10192",
            (Calyrex, "Ice") => "10193",
            (Calyrex, "Shadow") => "10194",
            // gmax forms skipped [10195-10228]
            (Growlithe, "Hisui") => "10229",
            (Arcanine, "Hisui") => "10230",
            (Voltorb, "Hisui") => "10231",
            (Electrode, "Hisui") => "10232",
            (Typhlosion, "Hisui") => "10233",
            (Qwilfish, "Hisui") => "10234",
            (Sneasel, "Hisui") => "10235",
            (Samurott, "Hisui") => "10236",
            (Lilligant, "Hisui") => "10237",
            (Zorua, "Hisui") => "10238",
            (Zoroark, "Hisui") => "10239",
            (Braviary, "Hisui") => "10240",
            (Sliggoo, "Hisui") => "10241",
            (Goodra, "Hisui") => "10242",
            (Avalugg, "Hisui") => "10243",
            (Decidueye, "Hisui") => "10244",
            (Dialga, "Origin") => "10245",
            (Palkia, "Origin") => "10246",
            (Basculin, "White") => "10247",
            (Enamorus, "Therian") => "10249",
            (Tauros, "Paldea Combat") => "10250",
            (Tauros, "Paldea Blaze") => "10251",
            (Tauros, "Paldea Aqua") => "10252",
            (Wooper, "Paldea") => "10253",
            (Dudunsparce, "Three-Segment") => "10255",
            (Palafin, "Hero") => "10256",
            (Maushold, "Family of Three") => "10257",
            (Tatsugiri, "Droopy") => "10258",
            (Tatsugiri, "Stretchy") => "10259",
            (Squawkabilly, "Blue") => "10260",
            (Squawkabilly, "Yellow") => "10261",
            (Squawkabilly, "White") => "10262",
            (Gimmighoul, "Roaming") => "10263",
            (Koraidon, "Limited") => "10264",
            (Koraidon, "Sprinting") => "10265",
            (Koraidon, "Swimming") => "10266",
            (Koraidon, "Gliding") => "10267",
            (Miraidon, "Low-Power") => "10268",
            (Miraidon, "Drive") => "10269",
            (Miraidon, "Aquatic") => "10270",
            (Miraidon, "Glide") => "10271",
            (Ursaluna, "Bloodmoon") => "10272",
            (Ogerpon, "Wellspring") => "10273",
            (Ogerpon, "Hearthflame") => "10274",
            (Ogerpon, "Cornerstone") => "10275",
            (Terapagos, "Terastal") => "10276",
            (Terapagos, "Stellar") => "10277",
            (Clefable, "Mega") => "10278",
            (Victreebel, "Mega") => "10279",
            (Starmie, "Mega") => "10280",
            (Dragonite, "Mega") => "10281",
            (Meganium, "Mega") => "10282",
            (Feraligatr, "Mega") => "10283",
            (Skarmory, "Mega") => "10284",
            (Froslass, "Mega") => "10285",
            (Emboar, "Mega") => "10286",
            (Excadrill, "Mega") => "10287",
            (Scolipede, "Mega") => "10288",
            (Scrafty, "Mega") => "10289",
            (Eelektross, "Mega") => "10290",
            (Chandelure, "Mega") => "10291",
            (Chesnaught, "Mega") => "10292",
            (Delphox, "Mega") => "10293",
            (Greninja, "Mega") => "10294",
            (Pyroar, "Mega") => "10295",
            (Floette, "Mega") => "10296",
            (Malamar, "Mega") => "10297",
            (Barbaracle, "Mega") => "10298",
            (Dragalge, "Mega") => "10299",
            (Hawlucha, "Mega") => "10300",
            (Zygarde, "Mega") => "10301",
            (Drampa, "Mega") => "10302",
            (Falinks, "Mega") => "10303",
            (Raichu, "Mega X") => "10304",
            (Raichu, "Mega Y") => "10305",
            (Chimecho, "Mega") => "10306",
            (Absol, "Mega Z") => "10307",
            (Staraptor, "Mega") => "10308",
            (Garchomp, "Mega Z") => "10309",
            (Lucario, "Mega Z") => "10310",
            (Heatran, "Mega") => "10311",
            (Darkrai, "Mega") => "10312",
            (Golurk, "Mega") => "10313",
            (Meowstic, "Mega") => "10314",
            (Crabominable, "Mega") => "10315",
            (Golisopod, "Mega") => "10316",
            (Magearna, "Normal-Mega") => "10317",
            (Magearna, "Original-Mega") => "10318",
            (Zeraora, "Mega") => "10319",
            (Scovillain, "Mega") => "10320",
            (Glimmora, "Mega") => "10321",
            (Tatsugiri, "Curly-Mega") => "10322",
            (Tatsugiri, "Droopy-Mega") => "10323",
            (Tatsugiri, "Stretchy-Mega") => "10324",
            (Baxcalibur, "Mega") => "10325",
            _ => pokemon.Species.Id.ToString()
        };
    }

    private static string GetAlcremieSprite(Pokemon pokemon)
    {
        if (pokemon.Pkm is not IFormArgument f)
            return Alcremie.Id().ToString();

        var formArgument = f.FormArgument;

        var flavor = pokemon.Form.Form.Name switch
        {
            "Caramel Swirl" => "caramel-swirl",
            "Lemon Cream" => "lemon-cream",
            "Matcha Cream" => "matcha-cream",
            "Mint Cream" => "mint-cream",
            "Rainbow Swirl" => "rainbow-swirl",
            "Ruby Cream" => "ruby-cream",
            "Ruby Swirl" => "ruby-swirl",
            "Salted Cream" => "salted-cream",
            "Vanilla Cream" => "vanilla-cream",
            _ => null
        };

        var topping = (AlcremieDecoration)formArgument switch
        {
            AlcremieDecoration.Strawberry => "strawberry-sweet",
            AlcremieDecoration.Berry => "berry-sweet",
            AlcremieDecoration.Clover => "clover-sweet",
            AlcremieDecoration.Flower => "flower-sweet",
            AlcremieDecoration.Love => "love-sweet",
            AlcremieDecoration.Ribbon => "ribbon-sweet",
            AlcremieDecoration.Star => "star-sweet",
            _ => null
        };

        if (flavor is null || topping is null)
            return Alcremie.Id().ToString();

        return $"{flavor}-{topping}";
    }

    private static string? GetFemaleSpriteId(this Pokemon pokemon)
    {
        var species = pokemon.Species.Species;

        return species switch
        {
            Venusaur or Butterfree or Rattata or Raticate or Pikachu or Raichu or Zubat or Golbat or Gloom or Vileplume
                or Kadabra or Alakazam or Doduo or Hypno or Rhyhorn or Rhydon or Goldeen or Seaking or Scyther
                or Magikarp or Gyarados or Eevee or Meganium or Ledyba or Ledian or Xatu or Sudowoodo or Politoed
                or Aipom or Wooper or Quagsire or Murkrow or Wobbuffet or Girafarig or Gligar or Steelix or Scizor
                or Heracross or Sneasel or Ursaring or Piloswine or Octillery or Houndoom or Donphan or Torchic
                or Combusken or Blaziken or Beautifly or Dustox or Ludicolo or Nuzleaf or Shiftry or Meditite
                or Medicham or Roselia or Gulpin or Swalot or Numel or Camerupt or Cacturne or Milotic or Relicanth
                or Starly or Staravia or Staraptor or Bidoof or Bibarel or Kricketot or Kricketune or Shinx or Luxio
                or Luxray or Roserade or Combee or Pachirisu or Buizel or Floatzel or Ambipom or Gible or Gabite
                or Garchomp or Hippopotas or Hippowdon or Croagunk or Toxicroak or Finneon or Lumineon or Snover
                or Abomasnow or Weavile or Rhyperior or Tangrowth or Mamoswine or Unfezant or Frillish or Jellicent
                or Pyroar or Espurr or Indeedee or Basculegion or Oinkologne
                when pokemon.Form.Form.IsNormal => species.Id().ToString(),
            Sneasel when pokemon.Form.Form.IsHisuian => "10235",
            _ => null
        };
    }
}
